# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "kiz"
client_id = "b73a018a508bc6692d829e04b596adbd"
application_url = "https://written-flow-assumed-jane.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://written-flow-assumed-jane.trycloudflare.com/auth/callback",
  "https://written-flow-assumed-jane.trycloudflare.com/auth/shopify/callback",
  "https://written-flow-assumed-jane.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-9b4e4108.myshopify.com"
